model_name_or_path: /mnt/xiyu/Model/Qwen/Qwen2.5-14B

stage: sft
do_train: true
finetuning_type: lora
lora_target: all

dataset: Qwen-2.5-14B_warmup
dataset_dir: data
template: qwen
cutoff_len: 16384
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16

output_dir: saves/llama3-8b/lora/sft
logging_steps: 5
save_strategy: epoch
plot_loss: true
overwrite_output_dir: true

per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1e-5
num_train_epochs: 2.0
lr_scheduler_type: constant_with_warmup
warmup_steps: 5
bf16: true
ddp_timeout: 180000000